project:
  type: website

website:
  title: "IS415 Team 15 Project"
  navbar:
    right:
      - icon: house-door-fill
        href: https://is415-team15-proj.netlify.app/
      - icon: github
        href: https://github.com/guga-nesh/IS415-Team-15-Proposal
  search: false

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

