project:
  type: website

website:
  title: "Team 15 Proposal"
  navbar:
    right:
      - icon: house-door-fill
        href: https://google.com
      - icon: github
        href: https://github.com/guga-nesh/IS415-Project
  search: false

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

